### ISSUE TITLE
adapting qt.py as compatibility layer?

### ISSUE THREAD

**Issue by dshlai** [theetcher/fxpt#2]
Hi! would you consider using qt.py (https://github.com/mottosso/Qt.py) as comaptibilty layer?

**Comment by theetcher** [comment]
Hi!
Actualy no need for this. Right now fxpt working in Maya 2016 (PySide) and Maya 2017 (PySide2) using my own ultra small Qt.py-like module. No need to support PyQt4 and PyQt5. Dont want issues from another system without need.

**Comment by dshlai** [comment]
That's quite fine then, since we only going to support Maya here.
