### ISSUE TITLE
Per User Config File

### ISSUE THREAD

**Issue by glm-nchaverou** [theetcher/fxpt#3]
Hey Eugene,
May I suggest a feature request ?
We're using Spark at our office and made a centralized install of the tool
However, we'd like to have a per user tools_list.yaml instead of all using the centralized version
Would that make sense ?

If you're busy, I may even do it myself if you'd like
I was thinking of fetching an environment variable (FX_SPARK_TOOLS_LIST_PATH) and concatenate the content of the user file with the main one

**Comment by theetcher** [comment]
It is already has per user configuration and history.
Type "Spark Configuration Directory" and it will open an explorer at
**C:/Users/USERNAME/AppData/Roaming/Damage Inc/fxpt/fx_spark.**
There you can find 
**tools_list_user.yaml**

**Comment by glm-nchaverou** [comment]
Sweet ! Haven't noticed that. Consider this ticked as closed :)
Thanks
